#FROM ubuntu:16.04
FROM openjdk:8u121-jdk

ENV UNDERSTAND_MINOR_VERSION 844
ENV UNDERSTAND_VERSION 4.0.$UNDERSTAND_MINOR_VERSION

RUN apt-get update && \
  apt-get install -y libglib2.0-0 libxext6 wget vim

RUN wget -qO- http://builds.scitools.com/all_builds/b$UNDERSTAND_MINOR_VERSION/Understand/Understand-$UNDERSTAND_VERSION-Linux-64bit.tgz \
    | tar -zxv

RUN echo "Server: scitools-license.devfactory.com 00000000 9000" > scitools/conf/license/locallicense.dat

ENV LD_LIBRARY_PATH /usr/lib/jvm/java-8-oracle/jre/lib/amd64:/scitools/bin/linux64
ENV PYTHONPATH /scitools/bin/linux64/python

WORKDIR /app

ENV PATH $PATH:/scitools/bin/linux64:/app/scripts


