spring:
  main:
    banner-mode: "off"
  jersey:
    application-path: /api

endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

app:
  analyzer:
    dataDir: ${ANALYZER_REPO_DIR:/Users/wrpinheiro/.deadCodeDetection/}
    scriptsDir: ${APP_SCRIPTS_DIR:/Users/wrpinheiro/mystuff/crossover/dead-code-detection/scripts/}
    scitoolsHome: ${APP_SCITOOLS_HOME:/Applications/scitools/bin/macosx}
